name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        run: docker build -t akshayrajput03/motoride-frontend -f BikeRideReactApp/Dockerfile .

    - name: Push Docker image
      run: |
        docker push akshayrajput03/motoride-frontend
